# Generated by Django 3.2.8 on 2021-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DmFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salesVolume', models.IntegerField()),
                ('introduce', models.CharField(max_length=64)),
                ('isFree', models.CharField(max_length=64)),
                ('specificLocation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DmGuangdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salesVolume', models.IntegerField()),
                ('introduce', models.CharField(max_length=64)),
                ('isFree', models.CharField(max_length=64)),
                ('specificLocation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DmSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salesVolume', models.IntegerField()),
                ('introduce', models.CharField(max_length=64)),
                ('isFree', models.CharField(max_length=64)),
                ('specificLocation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DmShanghai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salesVolume', models.IntegerField()),
                ('introduce', models.CharField(max_length=64)),
                ('isFree', models.CharField(max_length=64)),
                ('specificLocation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DmYunnan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salesVolume', models.IntegerField()),
                ('introduce', models.CharField(max_length=64)),
                ('isFree', models.CharField(max_length=64)),
                ('specificLocation', models.TextField()),
            ],
        ),
    ]
