# Generated by Django 3.2.8 on 2021-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRsale', '0002_dmxinjiang'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salesVolume', models.IntegerField()),
                ('introduce', models.CharField(max_length=64)),
                ('isFree', models.CharField(max_length=64)),
                ('specificLocation', models.TextField()),
            ],
        ),
    ]
